# Site settings
author: Sunitee
title: ## RESET 2020
header-img: img/home-bg.png
email: sunitee.mishra@gmail.com
copyright_name: Sunitee
description: > # this means to ignore newlines until "baseurl:"
  Do what is right, not what is easy.
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  s2umish

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
